Update build-openwrt.yml

diff --git a/.github/workflows/build-openwrt.yml b/.github/workflows/build-openwrt.yml
--- a/.github/workflows/build-openwrt.yml
+++ b/.github/workflows/build-openwrt.yml
@@ -87,28 +87,28 @@ jobs:
         [ -f $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config && echo 'Custom config loaded!' || echo 'No custom config!'
 
     - name: Apply patches
-  run: |
-    if [ -d $PATCHES_PATH ]; then
-      mv $PATCHES_PATH openwrt/$PATCHES_PATH
-    fi
-    cd openwrt
-    if [ -d $PATCHES_PATH ]; then
-      for FILE in $(ls $PATCHES_PATH | grep .patch); do 
-        echo "Applying $FILE" 
-        git apply --check $PATCHES_PATH/$FILE
-        if [ $? -eq 0 ]; then
-          git apply $PATCHES_PATH/$FILE 
-          echo "$FILE applied successfully"
-        else
-          echo "Failed to apply $FILE"
-          echo "Error details:"
-          git apply --check $PATCHES_PATH/$FILE || echo "Patch $FILE failed at this step."
-          git apply $PATCHES_PATH/$FILE || true
-          exit 1 
-        fi 
-      done
-    fi
-    git status -s
+      run: |
+        if [ -d $PATCHES_PATH ]; then
+          mv $PATCHES_PATH openwrt/$PATCHES_PATH
+        fi
+        cd openwrt
+        if [ -d $PATCHES_PATH ]; then
+          for FILE in $(ls $PATCHES_PATH | grep .patch); do 
+            echo "Applying $FILE" 
+            git apply --check $PATCHES_PATH/$FILE
+            if [ $? -eq 0 ]; then
+              git apply $PATCHES_PATH/$FILE 
+              echo "$FILE applied successfully"
+            else
+              echo "Failed to apply $FILE"
+              echo "Error details:"
+              git apply --check $PATCHES_PATH/$FILE || echo "Patch $FILE failed at this step."
+              git apply $PATCHES_PATH/$FILE || true
+              exit 1 
+            fi 
+          done
+        fi
+        git status -s
 
     - name: Download package
       id: package
@@ -178,12 +178,3 @@ jobs:
       with:
         retain_days: 7
         keep_minimum_runs: 2
-
-    - name: Remove old releases
-      uses: dev-drprasad/delete-older-releases@v0.1.0
-      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
-      with:
-        keep_latest: 2
-        delete_tags: true
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
